[[redirects]]
  from = "/"
  to = "/heart-talk.html"
  status = 200
  force = true

[[redirects]]
  from = "/scriptget.js"
  to = "/forbidden-page"
  status = 403

[[redirects]]
  from = "/scriptpost.js"
  to = "/forbidden-page"
  status = 403
