[[redirects]]
  from = "/"
  to = "/main.html"
  status = 200
  force = true

[[redirects]]
  from = "/js/scriptget.js"
  to = "/forbidden-page"
  status = 403

[[redirects]]
  from = "/js/scriptpost.js"
  to = "/forbidden-page"
  status = 403
